#!/usr/bin/env python
# This file is Python 2 compliant.

import os, sys

_srcdir = 'src/'
if getattr(sys, 'frozen', False):
    # The application is frozen
    _filepath = os.path.dirname(os.path.realpath(sys.executable))
else:
    _filepath = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(1, os.path.join(_filepath, _srcdir))

# if sys.version_info[0] == 3:
from AMA.main import ask
if __name__ == '__main__':
    ask()
